### ISSUE TITLE
calendar是否能增加禁用某段时间的功能

### ISSUE THREAD

**Issue by zhangYaRan** [ant-mini-program/mini-antui#108]

**Comment by Phieo** [comment]
能否描述更详细些？

**Comment by zhangYaRan** [comment]
> 能否描述更详细些？

传入一个时间段 2018-10-07至2018-10-10 这个时间段日历不可选择

**Comment by Phieo** [comment]
https://mobile.ant.design/components/calendar-cn/#components-calendar-demo-basic 参考这个 tagData新增disable属性，新增onSelectHasDisableDate表示选择区域中包含不可选日期

**Comment by Phieo** [comment]
0.4.0已经支持，文档可以先参考 [这个](https://github.com/ant-mini-program/mini-antui/blob/master/src/calendar/index.md)

**Comment by zhangYaRan** [comment]
> 0.4.0已经支持，可以文档先参考[这个](https://github.com/ant-mini-program/mini-antui/blob/master/src/calendar/index.md)

IOS（支付宝版本号:10.1.38）:点击上一个月份或者下一个月份，在onMonthChange回调中，tagData动态添加当前月份下的所有日期为disable: true，日历不渲染为禁用状态，Android没问题

**Comment by Phieo** [comment]
> > 0.4.0已经支持，可以文档先参考[这个](https://github.com/ant-mini-program/mini-antui/blob/master/src/calendar/index.md)
> 
> IOS（支付宝版本号:10.1.38）:点击上一个月份或者下一个月份，在onMonthChange回调中，tagData动态添加当前月份下的所有日期为disable: true，日历不渲染为禁用状态，Android没问题

我试了好像没问题啊 能提供下代码吗？

**Comment by zhangYaRan** [comment]
> > > 0.4.0已经支持，可以文档先参考[这个](https://github.com/ant-mini-program/mini-antui/blob/master/src/calendar/index.md)
> > 
> > 
> > IOS（支付宝版本号:10.1.38）:点击上一个月份或者下一个月份，在onMonthChange回调中，tagData动态添加当前月份下的所有日期为disable: true，日历不渲染为禁用状态，Android没问题
> 
> 我试了好像没问题啊 能提供下代码吗？


这个demo您看一下

const app = getApp();
Page({
  data: {
    dayTime: null,
    tagData: [],
  },
  onLoad(query) {
    my.getServerTime({
      success: (res) => {
        this.setData({
          'dayTime': res.time
        });
        var year = new Date(this.data.dayTime).getFullYear()
        var month = new Date(this.data.dayTime).getMonth()
        this.calcTime(year, month + 1)
      },
    });
  },
  onReady() {

  },
  onShow() {
    // 页面显示
  },
  onReachBottom() {

  },
  handleSelect(date) {
    console.log(date)
  },

  onMonthChange(month) {//切换月份
    var year = new Date(this.data.dayTime).getFullYear()
    this.calcTime(year, month + 1)
  },
  calcTime(year, month) {
    var that = this
    var temp = new Date(year, month, 0);
    var days = temp.getDate()
    var list = []
    month = parseInt(month, 10)
    for (var i = 1; i < days + 1; i++) {
      var time = new Date(year, parseInt(month) - 1, i, 23, 59, 59).getTime()
      var day = new Date(this.data.dayTime)//今天
      if (time <= day) {
        list.push({ date: year + '-' + month + '-' + (i < 10 ? '0' + i : i), disable: true, tag:'11'})
      }
    }
   
    that.setData({
      'tagData': list
    });
    console.log(that.data.tagData)
  }

})

**Comment by Phieo** [comment]
我看了你的代码
```javascript
f (time <= day) {
  list.push({ date: year + '-' + month + '-' + (i < 10 ? '0' + i : i), disable: true, tag:'11'})
}
```
这部分逻辑是不是有问题？

**Comment by zhangYaRan** [comment]
> 我看了你的代码
> 
> ```js
> f (time <= day) {
>   list.push({ date: year + '-' + month + '-' + (i < 10 ? '0' + i : i), disable: true, tag:'11'})
> }
> ```
> 
> 这部分逻辑是不是有问题？

tagData中的数据类型不是这种类型的吗 {date:'2018-09-30', disable:true,tag:'公积金'} 我这样拼接在安卓机型上没问题的，您那边测试的ios机型是没问题吗？这再测试下看看

**Comment by Phieo** [comment]
我的意思是 time <= day 这个条件 根本不会触发。

**Comment by zhangYaRan** [comment]
> 我的意思是 time <= day 这个条件 根本不会触发。

这个判断是：日历的当前月份每一天的毫秒数 只要小于今天毫秒数就会禁用
 例如当前月份是10月，点击上一个月份的时候是9月，9月份每一天的23点59分59秒毫秒数都会小于当天的毫秒数的，因此应该是可以禁用的。

**Comment by Phieo** [comment]
在点击下一月onMonthChange的时候这个条件并不会触发，你可以console看看

**Comment by zhangYaRan** [comment]
没错，点击上一个月的时候是可以触发的吧

**Comment by zhangYaRan** [comment]
> 在点击下一月onMonthChange的时候这个条件并不会触发，你可以控制台看看

没错，点击上一个月的时候是可以触发的吧

**Comment by Phieo** [comment]
可以先在push的时候用`(month < 10 ? '0' + month : month)`兼容下，后面发版本修复。

**Comment by zhangYaRan** [comment]
> 可以先在push的时候用`(month < 10 ? '0' + month : month)`兼容下，后面发版本修复。

好的

**Comment by Phieo** [comment]
你的建议收到了 后续会看情况优化 2这个点不错。
