### ISSUE TITLE
stepper步进器

### ISSUE THREAD

**Issue by yaoshanliang** [ant-mini-program/mini-antui#111]
stepper步进器达到最大值（最小）后加号会隐藏，此时setData当前值为1，加号不会自动显示，点击后可以显示。

**Comment by Phieo** [comment]
能提供下例子吗，看下来不是很明白

**Comment by yaoshanliang** [comment]
1、stepper点击+号到达最大值（比如10）；
2、点击一个按钮，该按钮的功能是将当期stepper值设置为1；
3、此时stepper右侧的+号还是灰掉的，但可点击；

**Comment by Phieo** [comment]
0.3.11修复
