### ISSUE TITLE
picker-item无onSelect

### ISSUE THREAD

**Issue by yaoshanliang** [ant-mini-program/mini-antui#117]
[https://docs.alipay.com/mini/component-ext/inputitem](https://docs.alipay.com/mini/component-ext/inputitem)
![image](https://user-images.githubusercontent.com/5028569/46719306-2dcc5680-cca0-11e8-9fe1-2db9ae76c5e1.png)
![image](https://user-images.githubusercontent.com/5028569/46719360-4dfc1580-cca0-11e8-87b1-43ddbf88cd93.png)

如图所示，使用onSelect报错，应该为onPickerTap

**Comment by Phieo** [comment]
已经修复。
