### ISSUE TITLE
[Vtabs]激活状态是否可以增加

### ISSUE THREAD

**Issue by labbomb** [ant-mini-program/mini-antui#125]
场景：tabs下套了vtabs，此时在vtabs上切换到任意位置，在切换tabs，此时vtabs激活状态还是刚才点击的位置。可否像tabs一样增加一个activeTab来控制，让它定位至初始状态。

**Comment by Phieo** [comment]
目前从技术上暂不支持，需要有个didMount之前的生命周期

**Comment by labbomb** [comment]
> 目前从技术上暂不支持，需要有个didMount之前的生命周期

不不不，不需要这么复杂，单独处理vtabs这个组件，和tabs的activeTab一样，增加一个新的激活属性来控制（选中的颜色，索引位置，状态等），和生命周期无关

**Comment by YeKao** [comment]
> > 目前从技术上暂不支持，需要有个didMount之前的生命周期
> 
> 不不不，不需要这么复杂，单独处理vtabs这个组件，和tabs的activeTab一样，增加一个新的激活属性来控制（选中的颜色，索引位置，状态等），和生命周期无关

我现在也遇到一个场景也需要一个属性来控制vtabs开启关闭，需要根据滚动条高度来判断是整个屏幕滑动还是vtabs滑动

**Comment by Phieo** [comment]
0.4.2新增了activeTab，可以参考下[文档](https://github.com/ant-mini-program/mini-antui/blob/master/src/vtabs/index.md)的示例代码
