### ISSUE TITLE
radio-group 无 class

### ISSUE THREAD

**Issue by yaoshanliang** [ant-mini-program/mini-antui#143]
[https://docs.alipay.com/mini/component/radio](https://docs.alipay.com/mini/component/radio)

![wx20181023-111247](https://user-images.githubusercontent.com/5028569/47333277-e210a880-d6b4-11e8-8073-bf5338d580b8.png)

![image](https://user-images.githubusercontent.com/5028569/47333317-066c8500-d6b5-11e8-9648-8da16ac869c5.png)

如图，radio-group 增加class无效

**Comment by pingan1927** [comment]
你好，感谢你的反馈，会尽快分析这个问题。
