### ISSUE TITLE
华为P20 显示有问题

### ISSUE THREAD

**Issue by yulongcs** [ant-mini-program/mini-antui#149]
华为P20， 系统：EMUI版本8.1.0， Android版本8.1.0, 支付宝版本：10.1.5，组件无法显示，

支付宝小程序打开小程序官方示例，显示不正常，扩展组件打开白屏

**Comment by Phieo** [comment]
小程序自定义组件是在基础库1.7.2时新增的 可以在小程序后台->设置->最低基础版本库 进行设置到1.7.2以上。小程序示例目前已经设置了最低版本库。
