### ISSUE TITLE
VTabs badgeType和badgeText无效

### ISSUE THREAD

**Issue by yaoshanliang** [ant-mini-program/mini-antui#151]
[https://docs.alipay.com/mini/component-ext/vtabs](https://docs.alipay.com/mini/component-ext/vtabs)

![image](https://user-images.githubusercontent.com/5028569/47486300-a28fbb00-d872-11e8-8688-6492e426be74.png)

如示例，设置badgeType和badgeText无效

**Comment by Phieo** [comment]
恩 可以试试最新版的0.4.0
