### ISSUE TITLE
message组件type为fail白屏

### ISSUE THREAD

**Issue by 349989153** [ant-mini-program/mini-antui#152]
**Describe the bug**
message组件type为fail的时候白屏。为success、info、warn、waiting的时候能正确显示

**To Reproduce**
<view class="page-message">
  <message
  title="title"
  subTitle="subTitle"
  type="fail"
 >
  </message>
</view>

**Expected behavior**
正确显示结果页

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
mini-antui: 0.3.12

**Comment by Phieo** [comment]
请更新到0.4.1 问题已经修复。
