### ISSUE TITLE
v-tabs组件 真机左侧tab不能跟随右侧滚动变化

### ISSUE THREAD

**Issue by rockyou9000** [ant-mini-program/mini-antui#160]
**v-tabs组件 真机左侧tab不能跟随右侧滚动变化**
模拟器正常, 真机会出现左侧tab无法点击, 无法跟随右侧tab滚动的情况

**截图**
![image](https://user-images.githubusercontent.com/17270758/47774654-99966200-dd28-11e8-9faf-c49203a331dd.png)

**Smartphone:**
 - Device: 华为p20
 - OS: android 8.1
 - 容器 Nebula

**Comment by Phieo** [comment]
是0.4.2版本吗？ 请参考下[文档](https://github.com/ant-mini-program/mini-antui/blob/master/src/vtabs/index.md)里的示例代码
