### ISSUE TITLE
tabs 左右滑动时需要增加事件

### ISSUE THREAD

**Issue by yaoshanliang** [ant-mini-program/mini-antui#162]
[https://docs.alipay.com/mini/component-ext/tabs](https://docs.alipay.com/mini/component-ext/tabs)

tab下content是根据点击的tab动态加载的，此时如果使用`swipeable `左右滑动并不会出发`onTabClick `，导致左右滑动时无法加载新tab下的数据，tab样式不会定位到新的tab下。

**Comment by Phieo** [comment]
用`onChange`可以吗

**Comment by yaoshanliang** [comment]
可以的
