### ISSUE TITLE
步进器 小数计算精度不准确

### ISSUE THREAD

**Issue by xieyanmei** [ant-mini-program/mini-antui#196]
**Describe the bug**
步进器的step设置为小数的时候，结果不准确 

**To Reproduce**
1. 设置step为0.01
2. 设置步进器value为4
3. 点击减号
4. 第二次点击的时候 得到的值为3.99-0.01=3.9800000000000004

**Expected behavior**
3.99-0.01=3.98

**Comment by Phieo** [comment]
0.4.12已经修复。
