### ISSUE TITLE
安装mini-antui后，无法读取webpack.config.babel.js配置文件

### ISSUE THREAD

**Issue by jijijiwinner** [ant-mini-program/mini-antui#228]
Cannot read property 'replace' of undefined
    at /Users/.../node_modules/webpack/lib/NormalModuleFactory.js:106:27
    at /Users/.../node_modules/webpack/lib/NormalModuleFactory.js:59:4
    at applyPluginsAsyncWaterfall (/Users/.../node_modules/webpack/lib/NormalModuleFactory.js:236:4)

**Comment by Phieo** [comment]
无法读取webpack.config.babel.js配置文件？和mini-antui有什么关系？
