### ISSUE TITLE
search-bar支持onchange事件吗

### ISSUE THREAD

**Issue by yaoshanliang** [ant-mini-program/mini-antui#251]
search-bar支持onchange事件吗？

**Comment by Phieo** [comment]
已经有onInput了 不会支持onChange

**Comment by yaoshanliang** [comment]
onInput 只会执行一次。想要onChange每次输入都执行

**Comment by Phieo** [comment]
基础组件input不支持onChange，search-bar基于input封装同样不会支持onChange
