### ISSUE TITLE
[AMIcon]组件不支持onTap事件么？

### ISSUE THREAD

**Issue by penxian** [ant-mini-program/mini-antui#257]
* 描述： 在使用AMicon图标时候 我注册了onTap事件，但是点击没有触发，难道小程序的text标签不能注册事件么？
`<am-icon type="delete" size="{{24}}" color="#333" data-index="{{1}}" onTap="delOption"></am-icon>`
`delOption(e){
    debugger
    const index =  e.target.dataset.index;
    this.$spliceData({'items':[index,1]});
  },`
* 当前行为：注册事件不触发
* 期望行为：注册onTap事件能触发方法

miniui版本："version": "0.4.22"

**Comment by Phieo** [comment]
当前不支持onTap事件，基础组件icon也不支持，你可以在外层包裹一个view处理
