### ISSUE TITLE
tab标签切换的时候，内容部分样式有问题

### ISSUE THREAD

**Issue by alonprince** [ant-mini-program/mini-antui#26]
**Describe the bug**
切换tab的时候，是通过translateX(-100%)来改变当前显示内容的，am-tabs-slides没有给width: 100%，所以am-tabs-slides是所有自己宽度的和，-100%就到空白部分了

**Additional context**
我改了下，但是不太熟github的协同工作流，所以这个提交和swipe-action的修改自动合并到一个pull request里面了

**Comment by Phieo** [comment]
已经在0.2.0修复
