### ISSUE TITLE
[AMIcon]组件样式默认则会有undefined样式

### ISSUE THREAD

**Issue by penxian** [ant-mini-program/mini-antui#261]
问题描述：https://github.com/ant-mini-program/mini-antui/blob/15a0945ab04ac2219b04a053bb1274621346df39/components/am-icon/index.axml#L2
处有个代码 {{className}}如果使用者不传入class则默认为undefined 请加上 {{className||''}}避免而外样式谢谢？
![image](https://user-images.githubusercontent.com/1733980/56871388-8ce09580-6a4f-11e9-9d3d-c3a6e7784ffe.png)

结果：默认不传值出现undefined
期望：默认不传值默认为空

**Comment by Phieo** [comment]
0.4.26 fixed
