### ISSUE TITLE
[bug]: v-tabs 组件语法问题

### ISSUE THREAD

**Issue by SoloJiang** [ant-mini-program/mini-antui#264]
Do you want to request a feature or report a bug?
bug
What is the current behavior?
语法错误
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code.
直接报错
What is the expected behavior?
`index.axml` 第 40 行 `scroll-y={{true}}` 漏掉了 `}`
Which versions of ``mini-antui``, and which version of ``Alipay`` are affected by this issue? Did this work in previous versions of ``mini-antui``?
master

**Comment by wssgcg1213** [comment]
https://github.com/ant-mini-program/mini-antui/blob/master/components/vtabs/index.axml#L40

**Comment by Phieo** [comment]
0.4.26 fixed
