### ISSUE TITLE
我怕不是中毒了，一天了，都用不了你们的组件

### ISSUE THREAD

**Issue by SilverLeaves** [ant-mini-program/mini-antui#268]
从示例里面复制出来的代码，都不行，我简直醉了，都快出神经病了
求给个痛快，解释一下

引入
![图片](https://user-images.githubusercontent.com/31165554/57608516-a92c1880-759f-11e9-8564-a55f42cf150e.png)

使用
![图片](https://user-images.githubusercontent.com/31165554/57608285-4b97cc00-759f-11e9-9795-f7430a4a77ef.png)

**Comment by Phieo** [comment]
https://docs.alipay.com/mini/component-ext/grid 看下文档先，或者你贴一下你的代码

**Comment by SilverLeaves** [comment]
@Phieo 代码贴在上面了，就是示例里面的代码，一点都不敢改

**Comment by Phieo** [comment]
我试了是没问题的，你看下你的版本号，以及你的JS部分代码有没有问题。

**Comment by SilverLeaves** [comment]
## 复现操作
1.打开小程序开发工具，新建项目
2.在项目打开`powershell`， 执行`yarn init -y`
3.安装mini-antui，执行`yarn add mini-antui`
4.使用在`pages/index/index.json`里面添加
```json
{
  "usingComponents":{
    "grid":"mini-antui/es/grid/index"
  }
}
```
5.复制`https://github.com/ant-mini-program/mini-antui/blob/master/examples/pages/grid/4/index.axml`里面的和`https://github.com/ant-mini-program/mini-antui/blob/master/examples/pages/grid/4/index.js`里面的代码进去

**Comment by Phieo** [comment]
提供下项目的目录结构

**Comment by SilverLeaves** [comment]
![图片](https://user-images.githubusercontent.com/31165554/57609760-1ccf2500-75a2-11e9-9805-d8e380f02269.png)

**Comment by Phieo** [comment]
真机预览可以吗？

**Comment by SilverLeaves** [comment]
![图片](https://user-images.githubusercontent.com/31165554/57610325-2a38df00-75a3-11e9-834d-a3db983af6d7.png)

**Comment by SilverLeaves** [comment]
真的非常感谢啦，我简直要疯啦
![enyci1bt](https://user-images.githubusercontent.com/31165554/57611011-80f2e880-75a4-11e9-80f9-8a02d8c64ba7.png)

**Comment by Phieo** [comment]
用小程序开发者工具新建项目，点击API示例，然后看下创建出来的小程序能够打开扩展组件-grid页面

![image](https://user-images.githubusercontent.com/10499704/57610993-79334400-75a4-11e9-9d21-1894f622a737.png)

**Comment by SilverLeaves** [comment]
这下可以了。
我把前面会出问题的页面放进去，也能运行了。
这简直太神奇了
 
![图片](https://user-images.githubusercontent.com/31165554/57611583-c7951280-75a5-11e9-9d3f-6492b2af2d5a.png)
