### ISSUE TITLE
[Feature request] 出一个typescript开发模板

### ISSUE THREAD

**Issue by SilverLeaves** [ant-mini-program/mini-antui#269]
Do you want to request a feature or report a bug?
A: Feature request
What is the current behavior?
A: Javascript开发
What is the expected behavior?
B: Typescript开发

**Comment by SilverLeaves** [comment]
可以支持stylus、less之类的css开发就更好了
![图片](https://user-images.githubusercontent.com/31165554/57685154-da711b00-7669-11e9-8134-fc63e0d39998.png)

**Comment by SilverLeaves** [comment]
我自己写了一个
https://github.com/SilverLeaves/ali-miniapp-ts-stylus-template

**Comment by Phieo** [comment]
这个feature 和组件库本身没关系吧
