### ISSUE TITLE
collapse组件在钉钉上无法展开，没有报错

### ISSUE THREAD

**Issue by SilverLeaves** [ant-mini-program/mini-antui#272]
Do you want to request a feature or report a bug?

What is the current behavior?
collapse组件在钉钉上无法展开，没有报错
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code.

What is the expected behavior?
像在支付宝上一样V，可以展开
Which versions of ``mini-antui``, and which version of ``Alipay`` are affected by this issue? Did this work in previous versions of ``mini-antui``?

version 0.4.26

**Comment by Phieo** [comment]
0.4.27 fixed
