### ISSUE TITLE
npm安装的无法读取自定义组件

### ISSUE THREAD

**Issue by 0123cf** [ant-mini-program/mini-antui#278]
npm安装后读取不到自定义组件。我手动在node_modules新建就可以。

这个问题是必现（在我的电脑上）

我经过测试发现，不用npm安装，然后写入依赖。这时候打开开发者工具会自动提示安装依赖，这时候就可以。

我发现一个问题是，npm安装的带有软链接的标志（不知道有没有说错）

**Comment by Phieo** [comment]
不能使用软链接的形式~请使用npm 替代 cnpm

**Comment by 0123cf** [comment]
🆗   可以科普下么？
