### ISSUE TITLE
请问有相似版本的H5 web组件库么

### ISSUE THREAD

**Issue by christianxiao** [ant-mini-program/mini-antui#280]
Do you want to request a feature or report a bug?
A feature。
我们已有一个小程序，现在小程序里面的某些页面需要在web端透出，希望不需要大的变更，请问有mini antui 对应的H5 web组件库么？

**Comment by Phieo** [comment]
可以看下这个 https://antui.alipay.com/

**Comment by christianxiao** [comment]
我看了下：
```目前 AntUI 只提供静态的规范样式，业务场景中的复杂效果以及配合 js 完成的交互效果需要业务自己控制。```
我们用的是React技术栈，如果有能直接使用的React组件就最好了

**Comment by Phieo** [comment]
暂时没有react版
