### ISSUE TITLE
建议提供类似微信9宫格照片以及预览的那种图片展示用扩展组件

### ISSUE THREAD

**Issue by emmetxu** [ant-mini-program/mini-antui#285]
目前支付宝的图片组件的展示方式都不太理想，类似微信9宫格那样的图片展示组件：图片按比例缩小按比例居中裁剪，放大后滚动预览原图，当然不限于9张照片了。

**Comment by Phieo** [comment]
能详细说明下吗？

**Comment by emmetxu** [comment]
> 能详细说明下吗？
在选择多张图片的展示，如果有扩展组件能支持类似微信的9宫格那样的样式展示就好了，非常漂亮。

现在多图轮播我用的是image组件结合scroll-view来实现的，图片按照scaleToFill模式展示，整个轮播的图片就压缩得厉害，显示不正常，没法类似微信那样居中等比例显示正常的图片。

然后点击图片，可以全屏轮播预览图片，删除图片，就像微信发朋友圈选择图片的那种交互体验，很棒。

**Comment by Phieo** [comment]
可以用my.previewImage
