### ISSUE TITLE
filter组件支持 mask 支持 onClose

### ISSUE THREAD

**Issue by WihteCrow** [ant-mini-program/mini-antui#287]
filter组件支持 mask 支持 onClose

**Comment by linxz** [comment]
近期的将会针对点击 mask 遮罩层做一个处理。:)

**Comment by linxz** [comment]
已经新增点击 mask 层关闭 filter 功能。

### 简要说明：
https://github.com/ant-mini-program/mini-antui/blob/master/components/filter/index.md#filter

### 代码示例：
`<filter onMaskTap="toggleFilter" ...`

```
Page({
  data: {
    show: true,
  },
  toggleFilter() {
    this.setData({
      show: !this.data.show,
    });
  }
});
```
