### ISSUE TITLE
search-bar 点击清除后输入框失焦

### ISSUE THREAD

**Issue by chenhebing** [ant-mini-program/mini-antui#289]
搜索组件，点击 clear 后，失去了焦点，这个交互不太合理，和 取消的交互一致了

看了下组件的 handleClear 里面注释了 获取焦点的代码，不清楚为啥要这么做？

```
 // this.setData({
 //   focus: true,
 // });
```

**Comment by chenhebing** [comment]
![image](https://user-images.githubusercontent.com/12512045/61698560-e1a05d80-ad6b-11e9-9b91-424fc94c89c0.png)

那目前是没法在清除的时候 获取焦点吗？

**Comment by linxz** [comment]
曾经这个自动获得会让某些安卓手机在使用搜狗输入法时出现问题。近期将会调整，换个方式处理。

**Comment by linxz** [comment]
已在 0.4.34 版本中修复该问题。
