### ISSUE TITLE
Can not find Component /node_modules/mini-antui/es/card/index in Page: pages/index/index

### ISSUE THREAD

**Issue by PlutoCA** [ant-mini-program/mini-antui#306]
![image](https://user-images.githubusercontent.com/31099607/69718350-16bd2200-1149-11ea-86d8-defe24187cf9.png)
老哥们这是啥问题，我看路径应该是没错的

**Comment by PlutoCA** [comment]
哎 今天打开 莫名其妙的又好了，太难了

**Comment by moonmirXD** [comment]
What's the solution here?
