### ISSUE TITLE
Tabs 组件切换bug

### ISSUE THREAD

**Issue by yulongcs** [ant-mini-program/mini-antui#71]
1. 多tab时，内容高度不统一的时候，每个tab-content按照高度最大的撑高了，
2. tab-content 滑动事件在内容区域，被撑高的地方无法滑动

**Comment by Phieo** [comment]
目前可以先用tab-content中使用scroll-view的方案替代，后面版本会修复。

**Comment by yaoshanliang** [comment]
这个大概哪个版本修复？

**Comment by Phieo** [comment]
0.4.0修复 月底前

**Comment by xieyanmei** [comment]
这个问题现在还没修复吗

**Comment by RoamIn** [comment]
这个因为用的 swiper-item 实现的原因吧，我在钉钉也是这样做的 tabs。
可是，tab-content 里面再有横向滚动的就懵逼了，和 swiper 组件的横向滚动混在一起，妙不可言...
话说，这个组件库，怎么从钉钉示例里面去掉了

**Comment by SilverLeaves** [comment]
在钉钉上，tabs组件内使用`scroll-view`，
1. 在模拟器上和手机上表现不一致，在手机上直接顶到tab里面了。
2. `scroll-view`纵向滑动经常莫名其妙的滑不动。

**Comment by vino1994** [comment]
我也遇到这个问题，这个组件问题挺多，不能滚动（加了scroll-view也不行），左右切换的时候高度不能自适应

**Comment by siqi-g** [comment]
2019年8月23日了, 还是没解决哦

**Comment by yaoshanliang** [comment]
@siqi-g 哈哈哈
