### ISSUE TITLE
【AntUI】组件样式和数量希望与支付宝 AntUI 对齐

### ISSUE THREAD

**Issue by David-CodingSerf** [ant-mini-program/mini-antui#86]
目前 AntUI 版本 10.1.10，请参考 https://antui.alipay.com/10.1.10/index.html
部分组件及格式缺失，请与之对齐，简单几例：
button组件没有，默认组件 button 并没有遵循 AntUI 规范，如：
### 小按钮没有，希望通过size直接设置：
![image](https://user-images.githubusercontent.com/5380960/45991884-6ae9f380-c0b9-11e8-9696-bba285e10e89.png)

### 规范中的button icon 及动效没有，希望增加icon props，内置规范图标：
![image](https://user-images.githubusercontent.com/5380960/45991899-86ed9500-c0b9-11e8-94cf-a7621a7ee7ac.png)

### 具体场景组件请支持，如：
![image](https://user-images.githubusercontent.com/5380960/45991926-af758f00-c0b9-11e8-9bb9-5f899d7ef40a.png)

诸如此类，等等等等。。

**Comment by Phieo** [comment]
基础组件已经有这些功能，等后续文档更新吧，具体可以看下小程序示例。
